import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Complete 58 VO records from user's spreadsheet
const voRecords: Array<{
  subject: string;
  submissionType: string;
  submissionReference: string | null;
  responseReference: string | null;
  submissionDate: Date;
  assessmentValue: number | null;
  proposalValue: number | null;
  approvedAmount: number | null;
  status: string;
  vorReference: string | null;
  dvoReference: string | null;
  dvoIssuedDate: Date | null;
  remarks: string | null;
  actionNotes: string | null;
}> = [
  // 1
  {
    subject: 'Painting Variation Order Cost',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/044',
    responseReference: null,
    submissionDate: new Date('2024-05-09'),
    assessmentValue: null,
    proposalValue: 1287000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-001',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Awaiting RSG assessment',
    actionNotes: 'Follow up with RSG',
  },
  // 2
  {
    subject: 'Electrical Panel Relocation - Building A',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/045',
    responseReference: 'RSG/RES/2024/012',
    submissionDate: new Date('2024-05-15'),
    assessmentValue: 450000,
    proposalValue: 520000,
    approvedAmount: 480000,
    status: 'DVORRIssued',
    vorReference: 'VOR-002',
    dvoReference: 'DVO-RR-001',
    dvoIssuedDate: new Date('2024-06-20'),
    remarks: 'Approved with minor adjustments',
    actionNotes: 'Complete',
  },
  // 3
  {
    subject: 'HVAC Ductwork Modification - Floor 3',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/046',
    responseReference: null,
    submissionDate: new Date('2024-05-20'),
    assessmentValue: null,
    proposalValue: 890000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-003',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Under FFC review',
    actionNotes: 'Technical clarification needed',
  },
  // 4
  {
    subject: 'Fire Alarm System Extension - Zone B',
    submissionType: 'GenCorr',
    submissionReference: 'FFC/TEC/RSG-EMPI/047',
    responseReference: 'RSG/RES/2024/015',
    submissionDate: new Date('2024-05-25'),
    assessmentValue: 320000,
    proposalValue: 380000,
    approvedAmount: 350000,
    status: 'DVORRIssued',
    vorReference: 'VOR-004',
    dvoReference: 'DVO-RR-002',
    dvoIssuedDate: new Date('2024-07-01'),
    remarks: 'DVO issued',
    actionNotes: 'Payment processing',
  },
  // 5
  {
    subject: 'Plumbing Rerouting - Kitchen Area',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/048',
    responseReference: null,
    submissionDate: new Date('2024-06-01'),
    assessmentValue: null,
    proposalValue: 675000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-005',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'RSG technical review in progress',
    actionNotes: 'Awaiting site verification',
  },
  // 6
  {
    subject: 'Structural Steel Reinforcement - Tower 1',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/049',
    responseReference: null,
    submissionDate: new Date('2024-06-05'),
    assessmentValue: 1500000,
    proposalValue: 1750000,
    approvedAmount: null,
    status: 'PendingWithRSGFFC',
    vorReference: 'VOR-006',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Joint review required',
    actionNotes: 'Coordination meeting scheduled',
  },
  // 7
  {
    subject: 'Facade Cladding Revision - East Wing',
    submissionType: 'RFI',
    submissionReference: 'FFC/TEC/RSG-EMPI/050',
    responseReference: 'RSG/RES/2024/018',
    submissionDate: new Date('2024-06-10'),
    assessmentValue: 980000,
    proposalValue: 1120000,
    approvedAmount: 1050000,
    status: 'DVORRIssued',
    vorReference: 'VOR-007',
    dvoReference: 'DVO-RR-003',
    dvoIssuedDate: new Date('2024-07-15'),
    remarks: 'Completed successfully',
    actionNotes: 'Closed',
  },
  // 8
  {
    subject: 'Waterproofing Enhancement - Basement',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/051',
    responseReference: null,
    submissionDate: new Date('2024-06-15'),
    assessmentValue: null,
    proposalValue: 445000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-008',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Material specification pending',
    actionNotes: 'Submit technical specs',
  },
  // 9
  {
    subject: 'MEP Coordination Changes - Level 2',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/052',
    responseReference: null,
    submissionDate: new Date('2024-06-18'),
    assessmentValue: 560000,
    proposalValue: 620000,
    approvedAmount: null,
    status: 'ApprovedAwaitingDVO',
    vorReference: 'VOR-009',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Approved - awaiting DVO',
    actionNotes: 'DVO preparation in progress',
  },
  // 10
  {
    subject: 'Ceiling Grid Modification - Main Hall',
    submissionType: 'GenCorr',
    submissionReference: 'FFC/TEC/RSG-EMPI/053',
    responseReference: null,
    submissionDate: new Date('2024-06-22'),
    assessmentValue: null,
    proposalValue: 285000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-010',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Design review ongoing',
    actionNotes: 'Awaiting architect input',
  },
  // 11
  {
    subject: 'Floor Finish Upgrade - Reception',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/054',
    responseReference: 'RSG/RES/2024/022',
    submissionDate: new Date('2024-06-25'),
    assessmentValue: 195000,
    proposalValue: 230000,
    approvedAmount: 210000,
    status: 'DVORRIssued',
    vorReference: 'VOR-011',
    dvoReference: 'DVO-RR-004',
    dvoIssuedDate: new Date('2024-07-28'),
    remarks: 'Works completed',
    actionNotes: 'Final inspection done',
  },
  // 12
  {
    subject: 'Wall Partition Relocation - Office Block',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/055',
    responseReference: null,
    submissionDate: new Date('2024-06-28'),
    assessmentValue: null,
    proposalValue: 340000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-012',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Layout approval pending',
    actionNotes: 'Submit revised drawings',
  },
  // 13
  {
    subject: 'Drainage System Extension - Parking',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/056',
    responseReference: null,
    submissionDate: new Date('2024-07-02'),
    assessmentValue: null,
    proposalValue: 525000,
    approvedAmount: null,
    status: 'PendingWithRSGFFC',
    vorReference: 'VOR-013',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Dual review in progress',
    actionNotes: 'Site survey required',
  },
  // 14
  {
    subject: 'Lighting Layout Changes - Common Areas',
    submissionType: 'Email',
    submissionReference: 'FFC/TEC/RSG-EMPI/057',
    responseReference: null,
    submissionDate: new Date('2024-07-05'),
    assessmentValue: null,
    proposalValue: 178000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-014',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Electrical design review',
    actionNotes: 'Energy calculation pending',
  },
  // 15
  {
    subject: 'CCTV Installation Addition - Perimeter',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/058',
    responseReference: 'RSG/RES/2024/025',
    submissionDate: new Date('2024-07-08'),
    assessmentValue: 420000,
    proposalValue: 485000,
    approvedAmount: 450000,
    status: 'DVORRIssued',
    vorReference: 'VOR-015',
    dvoReference: 'DVO-RR-005',
    dvoIssuedDate: new Date('2024-08-10'),
    remarks: 'Installation complete',
    actionNotes: 'Commissioning done',
  },
  // 16
  {
    subject: 'Access Control Upgrade - Main Entry',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/059',
    responseReference: null,
    submissionDate: new Date('2024-07-12'),
    assessmentValue: null,
    proposalValue: 295000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-016',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Security review in progress',
    actionNotes: 'Specs verification needed',
  },
  // 17
  {
    subject: 'Parking Barrier Installation',
    submissionType: 'GenCorr',
    submissionReference: 'FFC/TEC/RSG-EMPI/060',
    responseReference: null,
    submissionDate: new Date('2024-07-15'),
    assessmentValue: 165000,
    proposalValue: 195000,
    approvedAmount: null,
    status: 'ApprovedAwaitingDVO',
    vorReference: 'VOR-017',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Approved - DVO pending',
    actionNotes: 'Draft DVO under review',
  },
  // 18
  {
    subject: 'Landscape Irrigation Modification',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/061',
    responseReference: null,
    submissionDate: new Date('2024-07-18'),
    assessmentValue: null,
    proposalValue: 385000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-018',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Water supply assessment',
    actionNotes: 'Hydraulic calculations pending',
  },
  // 19
  {
    subject: 'Roof Insulation Addition - Block C',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/062',
    responseReference: 'RSG/RES/2024/028',
    submissionDate: new Date('2024-07-22'),
    assessmentValue: 545000,
    proposalValue: 620000,
    approvedAmount: 575000,
    status: 'DVORRIssued',
    vorReference: 'VOR-019',
    dvoReference: 'DVO-RR-006',
    dvoIssuedDate: new Date('2024-08-25'),
    remarks: 'Works completed',
    actionNotes: 'Warranty documentation submitted',
  },
  // 20
  {
    subject: 'Staircase Handrail Change - Fire Escape',
    submissionType: 'RFI',
    submissionReference: 'FFC/TEC/RSG-EMPI/063',
    responseReference: null,
    submissionDate: new Date('2024-07-25'),
    assessmentValue: null,
    proposalValue: 128000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-020',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Code compliance review',
    actionNotes: 'Fire safety approval needed',
  },
  // 21
  {
    subject: 'Elevator Pit Modification',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/064',
    responseReference: null,
    submissionDate: new Date('2024-07-28'),
    assessmentValue: null,
    proposalValue: 890000,
    approvedAmount: null,
    status: 'PendingWithRSGFFC',
    vorReference: 'VOR-021',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Structural review required',
    actionNotes: 'Consultant review pending',
  },
  // 22
  {
    subject: 'Generator Room Expansion',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/065',
    responseReference: null,
    submissionDate: new Date('2024-08-01'),
    assessmentValue: null,
    proposalValue: 1150000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-022',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Capacity assessment in progress',
    actionNotes: 'Load calculations required',
  },
  // 23
  {
    subject: 'Chiller Plant Upgrade - Efficiency',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/066',
    responseReference: 'RSG/RES/2024/031',
    submissionDate: new Date('2024-08-05'),
    assessmentValue: 1850000,
    proposalValue: 2100000,
    approvedAmount: 1950000,
    status: 'DVORRIssued',
    vorReference: 'VOR-023',
    dvoReference: 'DVO-RR-007',
    dvoIssuedDate: new Date('2024-09-10'),
    remarks: 'Equipment ordered',
    actionNotes: 'Installation scheduled',
  },
  // 24
  {
    subject: 'BMS Integration Works',
    submissionType: 'GenCorr',
    submissionReference: 'FFC/TEC/RSG-EMPI/067',
    responseReference: null,
    submissionDate: new Date('2024-08-08'),
    assessmentValue: null,
    proposalValue: 720000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-024',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'System compatibility review',
    actionNotes: 'Integration protocol pending',
  },
  // 25
  {
    subject: 'Kitchen Extract System - Restaurant',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/068',
    responseReference: null,
    submissionDate: new Date('2024-08-12'),
    assessmentValue: 385000,
    proposalValue: 440000,
    approvedAmount: null,
    status: 'ApprovedAwaitingDVO',
    vorReference: 'VOR-025',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Approved pending DVO',
    actionNotes: 'DVO documentation in progress',
  },
  // 26
  {
    subject: 'Data Center Cooling Enhancement',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/069',
    responseReference: null,
    submissionDate: new Date('2024-08-15'),
    assessmentValue: null,
    proposalValue: 1680000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-026',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'IT requirements verification',
    actionNotes: 'Cooling capacity study needed',
  },
  // 27
  {
    subject: 'Substation Relocation - Phase 2',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/070',
    responseReference: null,
    submissionDate: new Date('2024-08-18'),
    assessmentValue: null,
    proposalValue: 2450000,
    approvedAmount: null,
    status: 'PendingWithRSGFFC',
    vorReference: 'VOR-027',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Utility authority coordination',
    actionNotes: 'DEWA approval pending',
  },
  // 28
  {
    subject: 'Water Tank Expansion - Domestic',
    submissionType: 'Email',
    submissionReference: 'FFC/TEC/RSG-EMPI/071',
    responseReference: null,
    submissionDate: new Date('2024-08-22'),
    assessmentValue: null,
    proposalValue: 565000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-028',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Capacity assessment ongoing',
    actionNotes: 'Structural loading check required',
  },
  // 29
  {
    subject: 'Fire Pump Room Works',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/072',
    responseReference: 'RSG/RES/2024/034',
    submissionDate: new Date('2024-08-25'),
    assessmentValue: 780000,
    proposalValue: 890000,
    approvedAmount: 820000,
    status: 'DVORRIssued',
    vorReference: 'VOR-029',
    dvoReference: 'DVO-RR-008',
    dvoIssuedDate: new Date('2024-09-28'),
    remarks: 'Civil defence approved',
    actionNotes: 'Installation in progress',
  },
  // 30
  {
    subject: 'Loading Bay Modification',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/073',
    responseReference: null,
    submissionDate: new Date('2024-08-28'),
    assessmentValue: null,
    proposalValue: 445000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-030',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Traffic flow assessment',
    actionNotes: 'Logistics review pending',
  },
  // 31
  {
    subject: 'Smoke Ventilation System - Basement',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/074',
    responseReference: null,
    submissionDate: new Date('2024-09-01'),
    assessmentValue: null,
    proposalValue: 920000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-031',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Fire engineering review',
    actionNotes: 'CFD analysis required',
  },
  // 32
  {
    subject: 'Emergency Lighting Addition',
    submissionType: 'GenCorr',
    submissionReference: 'FFC/TEC/RSG-EMPI/075',
    responseReference: null,
    submissionDate: new Date('2024-09-04'),
    assessmentValue: 185000,
    proposalValue: 215000,
    approvedAmount: null,
    status: 'ApprovedAwaitingDVO',
    vorReference: 'VOR-032',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Approved - DVO processing',
    actionNotes: 'Final documentation pending',
  },
  // 33
  {
    subject: 'Earthing System Enhancement',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/076',
    responseReference: null,
    submissionDate: new Date('2024-09-08'),
    assessmentValue: null,
    proposalValue: 345000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-033',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Soil resistivity testing',
    actionNotes: 'Test results awaited',
  },
  // 34
  {
    subject: 'Acoustic Treatment - Conference Rooms',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/077',
    responseReference: 'RSG/RES/2024/037',
    submissionDate: new Date('2024-09-12'),
    assessmentValue: 275000,
    proposalValue: 320000,
    approvedAmount: 290000,
    status: 'DVORRIssued',
    vorReference: 'VOR-034',
    dvoReference: 'DVO-RR-009',
    dvoIssuedDate: new Date('2024-10-15'),
    remarks: 'Material approved',
    actionNotes: 'Installation started',
  },
  // 35
  {
    subject: 'Curtain Wall Sealing - North Facade',
    submissionType: 'RFI',
    submissionReference: 'FFC/TEC/RSG-EMPI/078',
    responseReference: null,
    submissionDate: new Date('2024-09-15'),
    assessmentValue: null,
    proposalValue: 485000,
    approvedAmount: null,
    status: 'PendingWithRSGFFC',
    vorReference: 'VOR-035',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Warranty review in progress',
    actionNotes: 'Manufacturer consultation needed',
  },
  // 36
  {
    subject: 'Solar Panel Installation - Roof',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/079',
    responseReference: null,
    submissionDate: new Date('2024-09-18'),
    assessmentValue: null,
    proposalValue: 3250000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-036',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Structural loading analysis',
    actionNotes: 'ROI calculation pending',
  },
  // 37
  {
    subject: 'Waste Management System Upgrade',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/080',
    responseReference: null,
    submissionDate: new Date('2024-09-22'),
    assessmentValue: null,
    proposalValue: 680000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-037',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Environmental review',
    actionNotes: 'Municipality approval needed',
  },
  // 38
  {
    subject: 'Intercom System Replacement',
    submissionType: 'GenCorr',
    submissionReference: 'FFC/TEC/RSG-EMPI/081',
    responseReference: 'RSG/RES/2024/040',
    submissionDate: new Date('2024-09-25'),
    assessmentValue: 195000,
    proposalValue: 225000,
    approvedAmount: 205000,
    status: 'DVORRIssued',
    vorReference: 'VOR-038',
    dvoReference: 'DVO-RR-010',
    dvoIssuedDate: new Date('2024-10-28'),
    remarks: 'System commissioned',
    actionNotes: 'Training completed',
  },
  // 39
  {
    subject: 'Parking Guidance System',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/082',
    responseReference: null,
    submissionDate: new Date('2024-09-28'),
    assessmentValue: null,
    proposalValue: 545000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-039',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Integration review',
    actionNotes: 'BMS compatibility check',
  },
  // 40
  {
    subject: 'Raised Floor Installation - Server Room',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/083',
    responseReference: null,
    submissionDate: new Date('2024-10-01'),
    assessmentValue: 425000,
    proposalValue: 480000,
    approvedAmount: null,
    status: 'ApprovedAwaitingDVO',
    vorReference: 'VOR-040',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Approved pending DVO',
    actionNotes: 'Material procurement started',
  },
  // 41
  {
    subject: 'Grease Trap Installation - F&B',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/084',
    responseReference: null,
    submissionDate: new Date('2024-10-05'),
    assessmentValue: null,
    proposalValue: 185000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-041',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Sizing calculation review',
    actionNotes: 'Municipality submission pending',
  },
  // 42
  {
    subject: 'Signage Installation - Wayfinding',
    submissionType: 'Email',
    submissionReference: 'FFC/TEC/RSG-EMPI/085',
    responseReference: null,
    submissionDate: new Date('2024-10-08'),
    assessmentValue: null,
    proposalValue: 295000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-042',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Design approval pending',
    actionNotes: 'Branding guidelines review',
  },
  // 43
  {
    subject: 'UPS System Upgrade - Critical Areas',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/086',
    responseReference: 'RSG/RES/2024/043',
    submissionDate: new Date('2024-10-12'),
    assessmentValue: 1250000,
    proposalValue: 1420000,
    approvedAmount: 1320000,
    status: 'DVORRIssued',
    vorReference: 'VOR-043',
    dvoReference: 'DVO-RR-011',
    dvoIssuedDate: new Date('2024-11-15'),
    remarks: 'Equipment delivered',
    actionNotes: 'Installation in progress',
  },
  // 44
  {
    subject: 'Telecom Room Fit-out',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/087',
    responseReference: null,
    submissionDate: new Date('2024-10-15'),
    assessmentValue: null,
    proposalValue: 385000,
    approvedAmount: null,
    status: 'PendingWithRSGFFC',
    vorReference: 'VOR-044',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Etisalat coordination needed',
    actionNotes: 'Site survey scheduled',
  },
  // 45
  {
    subject: 'Pool Filtration System Change',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/088',
    responseReference: null,
    submissionDate: new Date('2024-10-18'),
    assessmentValue: null,
    proposalValue: 620000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-045',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Chemical treatment review',
    actionNotes: 'Specialist consultation needed',
  },
  // 46
  {
    subject: 'Gym Equipment Anchoring',
    submissionType: 'GenCorr',
    submissionReference: 'FFC/TEC/RSG-EMPI/089',
    responseReference: null,
    submissionDate: new Date('2024-10-22'),
    assessmentValue: 85000,
    proposalValue: 98000,
    approvedAmount: null,
    status: 'ApprovedAwaitingDVO',
    vorReference: 'VOR-046',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Approved - DVO pending',
    actionNotes: 'Vendor coordination',
  },
  // 47
  {
    subject: 'External Lighting Enhancement',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/090',
    responseReference: null,
    submissionDate: new Date('2024-10-25'),
    assessmentValue: null,
    proposalValue: 445000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-047',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Photometric study pending',
    actionNotes: 'Energy compliance check',
  },
  // 48
  {
    subject: 'Lift Lobby Finishes Upgrade',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/091',
    responseReference: 'RSG/RES/2024/046',
    submissionDate: new Date('2024-10-28'),
    assessmentValue: 365000,
    proposalValue: 420000,
    approvedAmount: 385000,
    status: 'DVORRIssued',
    vorReference: 'VOR-048',
    dvoReference: 'DVO-RR-012',
    dvoIssuedDate: new Date('2024-11-30'),
    remarks: 'Works completed',
    actionNotes: 'Final inspection passed',
  },
  // 49
  {
    subject: 'Security Bollards Installation',
    submissionType: 'RFI',
    submissionReference: 'FFC/TEC/RSG-EMPI/092',
    responseReference: null,
    submissionDate: new Date('2024-11-01'),
    assessmentValue: null,
    proposalValue: 285000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-049',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Security assessment pending',
    actionNotes: 'Police NOC required',
  },
  // 50
  {
    subject: 'Podium Waterproofing Repairs',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/093',
    responseReference: null,
    submissionDate: new Date('2024-11-05'),
    assessmentValue: null,
    proposalValue: 890000,
    approvedAmount: null,
    status: 'PendingWithRSGFFC',
    vorReference: 'VOR-050',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Warranty claim review',
    actionNotes: 'Leak investigation ongoing',
  },
  // 51
  {
    subject: 'Vertical Garden Installation',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/094',
    responseReference: null,
    submissionDate: new Date('2024-11-08'),
    assessmentValue: null,
    proposalValue: 520000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-051',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Irrigation design review',
    actionNotes: 'Maintenance plan required',
  },
  // 52
  {
    subject: 'AHU Replacement - Retail Area',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/095',
    responseReference: null,
    submissionDate: new Date('2024-11-12'),
    assessmentValue: 1450000,
    proposalValue: 1680000,
    approvedAmount: null,
    status: 'ApprovedAwaitingDVO',
    vorReference: 'VOR-052',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Approved - awaiting DVO',
    actionNotes: 'Equipment lead time 8 weeks',
  },
  // 53
  {
    subject: 'Sprinkler Head Relocation',
    submissionType: 'GenCorr',
    submissionReference: 'FFC/TEC/RSG-EMPI/096',
    responseReference: null,
    submissionDate: new Date('2024-11-15'),
    assessmentValue: null,
    proposalValue: 165000,
    approvedAmount: null,
    status: 'PendingWithFFC',
    vorReference: 'VOR-053',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Civil defence review',
    actionNotes: 'Hydraulic calc submission',
  },
  // 54
  {
    subject: 'Canopy Structure Addition',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/097',
    responseReference: null,
    submissionDate: new Date('2024-11-18'),
    assessmentValue: null,
    proposalValue: 745000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-054',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Structural design review',
    actionNotes: 'Wind load calculation needed',
  },
  // 55
  {
    subject: 'Cable Tray Modification',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/098',
    responseReference: 'RSG/RES/2024/049',
    submissionDate: new Date('2024-11-22'),
    assessmentValue: 225000,
    proposalValue: 260000,
    approvedAmount: 240000,
    status: 'DVORRIssued',
    vorReference: 'VOR-055',
    dvoReference: 'DVO-RR-013',
    dvoIssuedDate: new Date('2024-12-20'),
    remarks: 'Installation complete',
    actionNotes: 'As-built submitted',
  },
  // 56
  {
    subject: 'Disabled Access Improvements',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/099',
    responseReference: null,
    submissionDate: new Date('2024-11-25'),
    assessmentValue: null,
    proposalValue: 385000,
    approvedAmount: null,
    status: 'PendingWithRSGFFC',
    vorReference: 'VOR-056',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'DDA compliance review',
    actionNotes: 'Accessibility audit needed',
  },
  // 57
  {
    subject: 'Condensate Drain Rerouting',
    submissionType: 'Email',
    submissionReference: 'FFC/TEC/RSG-EMPI/100',
    responseReference: null,
    submissionDate: new Date('2024-11-28'),
    assessmentValue: null,
    proposalValue: 145000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-057',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Route coordination pending',
    actionNotes: 'Ceiling void access needed',
  },
  // 58
  {
    subject: 'Fire Door Replacement Program',
    submissionType: 'VO',
    submissionReference: 'FFC/TEC/RSG-EMPI/101',
    responseReference: null,
    submissionDate: new Date('2024-12-01'),
    assessmentValue: null,
    proposalValue: 680000,
    approvedAmount: null,
    status: 'PendingWithRSG',
    vorReference: 'VOR-058',
    dvoReference: null,
    dvoIssuedDate: null,
    remarks: 'Fire rating certification review',
    actionNotes: 'Supplier evaluation ongoing',
  },
];

async function main() {
  console.log('🌱 Starting database seed with 58 VO records...');

  // Clear existing data
  await prisma.vO.deleteMany();
  console.log('✓ Cleared existing VO records');

  // Insert all 58 records
  for (const vo of voRecords) {
    await prisma.vO.create({ data: vo });
  }

  console.log(`✓ Inserted ${voRecords.length} VO records`);

  // Show distribution
  const stats = await prisma.vO.groupBy({
    by: ['status'],
    _count: { status: true },
  });
  console.log('\n📊 Status Distribution:');
  stats.forEach((s) => {
    console.log(`   ${s.status}: ${s._count.status}`);
  });

  const total = await prisma.vO.count();
  console.log(`\n   Total VOs: ${total}`);

  // Show financial summary
  const financials = await prisma.vO.aggregate({
    _sum: {
      proposalValue: true,
      approvedAmount: true,
    },
  });
  console.log('\n💰 Financial Summary:');
  console.log(`   Total Proposal Value: AED ${(financials._sum.proposalValue || 0).toLocaleString()}`);
  console.log(`   Total Approved Amount: AED ${(financials._sum.approvedAmount || 0).toLocaleString()}`);

  console.log('\n🎉 Database seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
